### PR TITLE
Added DE & TBY tokens to Polygon network

### PR DESCRIPTION
**Pull request by cyb3rKn1ght**

### CODE REVIEW

**Comment by djdeniro** [comment]
$DE and $TBY already listed in 1inch and Metamask token list 

[website](denet.pro)

DeNet File Token https://www.coingecko.com/en/coins/denet-file-token

$TBY is storage gastoken, can issue via $DE only. And burn after datakeepers store files for proofs.

[Deposit DAPP](https://pay.denet.app)
[Consensus DAPP](https://consensus.denet.app)

**Comment by cyb3rKn1ght** [comment]
@zekraken-bot could you take a look at the pull request please?:)

**Comment by cyb3rKn1ght** [comment]
@zekraken-bot done

**Comment by cyb3rKn1ght** [comment]
@zekraken-bot made them in the checksum format

**Comment by cyb3rKn1ght** [comment]
@zekraken-bot Thank you! But it seems I forgot to ask where I should add links to these token images.

**Pull request merged**
