### PR TITLE
Update tokens.ts

### PR DESCRIPTION
**Pull request by sanchitdawarsd**

### CODE REVIEW

**Comment by sanchitdawarsd** [comment]
Hi there, so we are building a Liquidity engine for balancer and uniswap based pool where we are creating merkle based rewards system to deep the liquidity and our token will help as a part of process deepening onchain liquidity

**Comment by timjrobinson** [comment]
Hi @sanchitdawarsd what is the actual project though? Can you link to a website that describes it.

**Comment by sanchitdawarsd** [comment]
we are currently in building mode here the website staybull.fi , need a balancer 80-20 pool to continue the progress on our merkl based smart contracts

**Comment by sanchitdawarsd** [comment]
please merge ser

**Pull request closed without merging**
